// List of Arrays - special,lowercase,uppercase and number
var characterLength = 8;
var answer = [];

var specialChar = ['!','@','#','$','%','^','&','*','(',')','<','>',];
var lowerCase = ['a', 'b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',];
var upperCase = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',];
var number = ['1', '2','3','4','5','6','7','8','9','0',];

// Assignment Code
var generateBtn = document.querySelector("#generate");

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);

// Write password to the #password input - added write password fucntion
function writePassword() {
   
    var correctPrompts = showPrompt(); 
  
    if(correctPrompts) {
      var newPassword = generatePassword();
      var passwordText = document.querySelector("#password");
    
      passwordText.value = newPassword;
    } else {
     passwordText.value = "";
    }
}
    
    
// Generate Password Fuction - set a loop based on prompts, loop will keep going for however long the selected character length is 
    function generatePassword() {
        var password = '';
        for(var i = 0; i < characterLength; i++){
            var randomIndex = Math.floor(Math.random() * answer.length);
            password = password + answer[randomIndex];
        }
        return password;
    }
    


//call showPrompt fuction - passwords generated by a list of prompts
function showPrompt(){
  answer = [];
  
  characterLength = parseInt (prompt("How many charcaters would you like your password to contain?"));
   if(isNaN(characterLength) || characterLength < 8 || characterLength > 128) {
      alert("Password lenth must be provided as a number between , 8 - 128 characters. Please try again.");
      return false;
   }

    if (confirm("Click OK to confirm including lowercase characters?")){
      answer = answer.concat(lowerCase);
    }
    if (confirm("Click OK to confirm including uppercase characters?")){
      answer = answer.concat(upperCase);
    }
      if (confirm("Click OK to confirm include special characters?")){
        answer = answer.concat(specialChar);
      }

      if (confirm("Click OK to confirm numeric characters?")){
        answer = answer.concat(number);
      }
      return true;

    }
