// List of Arrays - special,lowercase,uppercase and number
var characterLength = 8;
var answer = [];

var specialChar = ['!','@','#','$','%','^','&','*','(',')','<','>',];
var lowerCase = ['a', 'b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',];
var upperCase = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',];
var number = ['1', '2','3','4','5','6','7','8','9','0',];

// Assignment Code
var generateBtn = document.querySelector("#generate");

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);

// Write password to the #password input - added write password fucntion
function writePassword() {
   
    var correctPrompts = showPrompt(); 
  
    if(correctPrompts) {
      var newPassword = generatePassword();
      var passwordText = document.querySelector("#password");
    
      passwordText.value = newPassword;
    } else {
     passwordText.value = '';
    }
}
    
    
// Generate Password Fuction
    function generatePassword() {
        var password = '';
        for(var i = 0; i < characterLength; i++){
            var randomIndex = Math.floor(Math.random() * answer.length);
            password = password + answer[randomIndex];
        }
        return password;
    }
    


//call showPromt fuction - passwords generated by promts
function showPrompt(){
  answer = [];
  
  characterLength = parseInt (prompt("How many charcaters do you want your password to be? (8 -128 characters"));
   if(isNaN(characterLength) || characterLength < 8 || characterLength > 128) {
      alert("Character length has to be a number, 8 - 128 characters. Please try again.");
      return false;
   }

    if (confirm("Would you like lowercase letters in your password?")){
      choiceArr = answer.concat(lowerCase);
    }
    if (confirm("Would you like uppercase letters in your password?")){
      choiceArr = answer.concat(upperCase);
    }
      if (confirm("Would you like special characters in your password?")){
        answer = answer.concat(specialChar);
      }

      if (confirm("Would you like numbers in your password?")){
        answer = answer.concat(number);
      }
      return true;

    }
